import SquadList from "./SquadList";
import HeadingStyle1 from "../Headings/HeadingStyle1";

function SquadSection() {
  const heading = "Squad";
  const title = "Independent AI Teams ";
  const description1 =
    "Value generated by AI is centralised into a few companies, often resulting in a lack of innovation or worse, detrimental technologies to society. We are building an alternative to the traditional industry or academia choice for AI talent. We believe that independent teams will generally work on use cases that are better for the world.";
  const description2 =
    "Algovera is made up of independent AI teams (called Squads), funded by Algovera Grants and building on Algovera infrastructure, to create useful AI applications. Squads can leverage the resources of Algovera's AI commons (data, talent, captial, infrastucture, etc) to compete in the market. Here are some already building within Algovera:";

  return (
    <div className="space-y-6">
      <HeadingStyle1
        heading={heading}
        title={title}
        description1={description1}
        description2={description2}
      />
      <div className="flex justify-between">
        <h2 className="section-heading pl-3">Algovera Squads</h2>
        <a
          className="justify-self-end underline underline-offset-4 decoration-primary pr-8"
          href="https://algovera.notion.site/Squads-194768658a044302a0cdc24d5d758b9d"
          target="_blank"
          rel="noopener noreferrer"
        >
          Explore All
        </a>
      </div>
      <SquadList />
    </div>
  );
}

export default SquadSection;
